openapi: 3.0.4
info:
  title: Complaints API
  description: API contract containing requests for Complaints domain.
  version: 0.0.1

paths:
  /complaints:
    put:
      summary: Creates new Complaint.
      operationId: createComplaint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./definitions/complaint-request.yml#/ComplaintRequest"
      responses:
        '201':
          description: Complaint created successfully.
        '400':
          description: Bad request.
    get:
      summary: Gets all Complaints.
      operationId: getAllComplaints
      responses:
        '200':
          description: Response containing all Complaints.
          content:
            application/json:
              schema:
                $ref: "./definitions/complaints-collection.yml#/ComplaintsCollection"
  /complaints/{id}/updateContent:
    post:
      summary: Updates content of existing Complaint.
      operationId: updateComplaintContent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./definitions/complaint-content.yml#/ComplaintContent"
      responses:
        '200':
          description: Complaint content updated successfully.
        '400':
          description: Bad request.
        '404':
          description: Complaint not found.


